config/routes.rb
Rails.application.routes.draw do
  
  # Ewidencja
  resources :teams do
    resources :schools, only: [:edit, :update, :new, :create, :destroy] do
      resources :officials, only: [:edit, :update, :new, :create, :destroy]
    end
    resources :scouts, only: [:show, :edit, :update, :new, :create, :destroy] do
      resources :parents, only: [:edit, :update, :new, :create, :destroy]
      resources :individual_tasks, only: [:index, :edit, :update, :new, :create, :destroy]
    end
    resources :goals, only: [:index, :edit, :update, :new, :create, :destroy]
  end
  
  # Edukacja
  resources :tasks
  
  # Planowanie
  resources :events do
    resource :sort_activities_order, only: [:edit, :update], controller: 'activities/sort_order'
    resources :activities, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :execution_reports, only: [:index]
  end
  
  # Ocena
  delete "scores/:team_id", to: "scores#clear", as: "clear_scores"
  resources :scores, only: [:index, :show, :new, :create, :destroy]
  
  # Zarządzanie danymi
  
  resources :profiles, only: [:edit, :update]
  
  get "home/download_pdf"
  
  get '/admin', to: 'admin#index'
  namespace :admin do
    resources :abilities
    resources :activity_forms
    resources :character_traits, only: [:index, :edit, :update, :new, :create, :destroy]
  end
  
  root to: 'home#index'

  devise_for :users

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  after_initialize :set_execution_report

  # Associations
  belongs_to :event
  has_and_belongs_to_many :activity_forms, join_table: "activity_forms_activities"
  has_one :execution_report, dependent: :destroy
  
  accepts_nested_attributes_for :execution_report
  
  # Validations
  validates :name, presence: true
  validates :estimated_time, presence: true
  
  # Scopes
  scope :ordered, -> { order("position") }
  
  private
  
  def set_execution_report
    build_execution_report if execution_report.nil?
  end
  
end

app/models/task.rb
class Task < ActiveRecord::Base

  after_save :set_score
  before_save :default_values

  # Associations
  has_one :score, as: :scorable, dependent: :destroy, dependent: :destroy
  belongs_to :activity_form
  belongs_to :taskable, polymorphic: true
  belongs_to :team, -> { where(tasks: {taskable_type: 'Team'}) }, foreign_key: 'taskable_id'
  belongs_to :scout, -> { where(tasks: {taskable_type: 'Scout'}) }, foreign_key: 'taskable_id'
  
  # Validations
  validates :activity_form, presence: true
  validates :description, presence: true
  validates :deadline, presence: true
  
  # Enums
  enum status: %i(in_progress accomplished failed)
  
  def set_score
    if accomplished? && score.nil? && taskable_type == "Scout"
      build_score(scout_id: taskable_id, number: points, scorable_id: id, scorable_type: self.class.name)
      save
    elsif in_progress? && score.present? && taskable_type == "Scout"
      score.destroy
    end
  end
  
  def default_values
    self.points ||= 0
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_and_authorize_task,
    only: [:show, :edit, :update, :destroy]
  before_filter :set_breadcrumbs

  def index
    authorize Task
    
    @individual_tasks = policy_scope(Task.where(taskable_type: "Scout")).page(params[:page]).per(20)
    @individual_tasks = PaginatingDecorator.decorate(@individual_tasks, with: TaskDecorator)
    
    @goals = policy_scope(Task).where(taskable_type: "Team").page(params[:page]).per(20)
    @goals = PaginatingDecorator.decorate(@goals, with: TaskDecorator)
  end

  def show
    @task = TaskDecorator.decorate(@task)
    add_breadcrumb @task.activity_form_name
  end

  def new
    @task = Task.new
    @type = params[:type]
    authorize @task
    add_breadcrumb t(".title")
  end

  def edit
    add_breadcrumb @task.activity_form.name, @task
    add_breadcrumb t(".title")
  end

  def create
    @task = Task.new(task_params)
    authorize @task

    if @task.save
      redirect_to tasks_path, notice: t(".notice")
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: t(".notice")
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: t(".notice")
  end

  private

  def load_and_authorize_task
    @task = Task.find(params[:id])
    authorize @task
  end
  
  def load_and_authorize_team
    @team = Team.find(params[:team_id])
    @team = TeamDecorator.decorate(@team)
    authorize @team
  end
  
  def load_and_authorize_scout
    @scout = Scout.find(params[:scout_id])
    @scout = ScoutDecorator.decorate(@scout)
    authorize @scout
  end

  def task_params
    params.require(:task).permit(*policy(@task || Task).permitted_attributes)
  end
  
  def set_breadcrumbs
    add_breadcrumb t("menu.training"), tasks_path
  end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_status_options_for_select
    Task.statuses.keys.map do |key|
      [I18n.t("enumerations.task.status.#{key}"), key]
    end
  end
  
  def task_taskable_id_options_for_select(type)
    if type == "Scout" 
      policy_scope(Scout).map do |scout|
        ["#{scout.first_name} #{scout.last_name}", scout.id]
      end
    else
      policy_scope(Team).map do |team|
        [team.name, team.id]
      end
    end
  end
  
end

app/views/tasks/_form.html.haml
= simple_form_for(@task, url: url, html: { class: 'form-horizontal' }) do |f|

  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@parent.errors.count, "error")} prohibited this parent from being saved:"
      %ul
        - @parent.errors.full_messages.each do |msg|
          %li= msg
          
  = f.input :taskable_id, as: :hidden
  = f.input :taskable_type, as: :hidden

  .row
    .input-field.col.s4
      = f.association :activity_form, :collection => policy_scope(ActivityForm.all), :value_method => :id, label: false
      = f.label :activity_form, active: true
      
    .input-field.col.s4
      = f.text_field :deadline, as: :date, class: 'datepicker'
      = f.label :deadline
      
    .input-field.col.s4
      = f.select :status, task_status_options_for_select, include_blank: false
      = f.label :status
      
  .row
    .input-field.col.s12
      = f.text_area :description, class: "materialize-textarea"
      = f.label :description
      
  = submit_button_for t("nav.send"), icon="send"

app/views/tasks/_support.html.haml
.card-panel
  %h5= t(".title")
  .center-align.hint= t(".instruction")
  .card-content
    %table
      %thead
        %tr
          %th= t(".activity_form")
          %th= t(".description")
          %th= t(".character_traits")
          %th
          %th= icon_link_to("#", "add", class: "inactive")
      %tbody
        -activity_forms.each do |activity_form, character_traits|
          %tr
            %td= activity_form.name
            %td= activity_form.description
            %td= character_traits.join(", ")
            %td
            %td= icon_link_to(new_team_scout_task_path(@team, @scout, activity_form: activity_form, character_traits: character_traits), "add", class: "success")

app/views/tasks/_tasks.html.haml
.right
  = button_link_to t(".add"), new_task_path(type: taskable_type), "add", true

%table
  %thead
    %tr
      %th= t(".activity_form")
      %th= t(".taskable_name")
      %th= t(".status")
      %th= icon_link_to("#", "check", class: "inactive")
      %th= icon_link_to("#", "close", class: "inactive")
      %th= t(".deadline")
      - if taskable_type == "Scout"
        %th= t(".points")
      %th
      - if taskable_type == "Team"
        %th= icon_link_to("#", "event_note", class: "inactive")
      %th= icon_link_to("#", "edit", class: "inactive")
      %th= icon_link_to("#", "delete", class: "inactive")

  %tbody
    - tasks.sort_by(&:deadline).each do |task|
      %tr
        %td= link_to task.activity_form_name, task_path(task)
        %td= link_to task.taskable_name, taskable_type == "Scout" ? team_scout_path(task.taskable.team, task.taskable) : team_path(task.taskable)
        %td= task.status
        - if task.in_progress?
          %td= icon_link_to(task_path(task, task: {taskable: task.taskable, status: "accomplished"}), "check", method: :patch, class: "success")
          %td= icon_link_to(task_path(task, task: {taskable: task.taskable, status: "failed"}), "close", method: :patch, class: "danger")
        - else
          %td
          %td
        %td= task.deadline
        - if taskable_type == "Scout"
          %td= task.points
        %td
        - if taskable_type == "Team" && Event.nearest.first.present?
          %td= icon_link_to(new_event_activity_path(event_id: Event.nearest.first.id, activity: {activity_form_ids: [task.activity_form_id], description: task.description}), "event_note", class: "success")
        - elsif taskable_type == "Team"
          %td
        %td= icon_link_to(edit_task_path(task), "edit")
        %td= icon_link_to(task_path(task), "delete", method: :delete, data: { confirm: t(".confirm_destroy") }, class: "danger")
        
= paginate tasks

app/views/tasks/edit.html.haml
- content_for :title do
  = t(".title")
- content_for :breadcrumbs do
  = render_breadcrumbs
  
= simple_form_for(@task, html: { class: 'form-horizontal' }) do |f|

  - if @task.errors.any?
    #error_explanation
      %h5= t("activerecord.errors.message", count: @task.errors.count)
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg
          
  = f.input :taskable_id, as: :hidden
  = f.input :taskable_type, as: :hidden
  
  .row 
    - if @task.taskable_type == "Scout"
      .input-field.col.s6
        = f.input :points, input_html: {value: '0'}
        = f.label :points, active: true
  .row
    .input-field.col.s4
      = f.association :activity_form, :collection => policy_scope(ActivityForm.all), :value_method => :id, label: false, include_blank: false
      = f.label :activity_form, active: true
      
    .input-field.col.s4
      = f.text_field :deadline, as: :date, class: 'datepicker'
      = f.label :deadline
      = f.hint "Wybierz datę ponownie"
      
    .input-field.col.s4
      = f.select :status, task_status_options_for_select, include_blank: false
      = f.label :status
      
  .row
    .input-field.col.s12
      = f.text_area :description, class: "materialize-textarea"
      = f.label :description
      
  = submit_button_for t("nav.send"), icon="send"

app/views/tasks/index.html.haml
- content_for :title do
  = t(".title")
- content_for :notice do
  = notice
- content_for :breadcrumbs do
  = render_breadcrumbs
  
%ul.collapsible{"data-collapsible" => "expandable"}
  %li
    .collapsible-header.active
      %h5= t(".individual_tasks")
    .collapsible-body
      = render partial: "tasks", locals: {tasks: @individual_tasks, taskable_type: "Scout"}
  %li
    .collapsible-header.active
      %h5= t(".goals")
    .collapsible-body
      = render partial: "tasks", locals: {tasks: @goals, taskable_type: "Team"}

app/views/tasks/new.html.haml
- content_for :title do
  = t(".title")
- content_for :breadcrumbs do
  = render_breadcrumbs

= simple_form_for(@task, html: { class: 'form-horizontal' }) do |f|

  - if @task.errors.any?
    #error_explanation
      %h5= t("activerecord.errors.message", count: @task.errors.count)
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg
  .row 
    .input-field.col.s6     
      = f.select :taskable_id, task_taskable_id_options_for_select(@type), include_blank: false
      = f.label :taskable_id, active: false
    
    - if @type == "Scout"
      = f.input :taskable_type, as: :hidden, input_html: {value: 'Scout'}
    - elsif @type == "Team"
      = f.input :taskable_type, as: :hidden, input_html: {value: 'Team'}
      
    - if @type == "Scout"
      .input-field.col.s6
        = f.input :points, input_html: {value: '0'}, label: false
        = f.label :points, active: true
  .row
    .input-field.col.s4
      = f.association :activity_form, :collection => policy_scope(ActivityForm.all), :value_method => :id, label: false, include_blank: false
      = f.label :activity_form, active: true
      
    .input-field.col.s4
      = f.text_field :deadline, as: :date, class: 'datepicker'
      = f.label :deadline
      
    .input-field.col.s4
      = f.select :status, task_status_options_for_select, include_blank: false
      = f.label :status
      
  .row
    .input-field.col.s12
      = f.text_area :description, class: "materialize-textarea"
      = f.label :description
      
  = submit_button_for t("nav.send"), icon="send"

app/views/tasks/show.html.haml
- content_for :notice do
  = notice
- content_for :breadcrumbs do
  = render_breadcrumbs
  
.card-panel
  .right
    
    - if @task.taskable_type == "Team" && Event.nearest.first.present?
      = menu_link_to(t(".assign_to_event"), new_event_activity_path(event_id: Event.nearest.first.id, activity: {activity_form_ids: [@task.activity_form_id], description: @task.description}), "event_note", class: "success btn-flat")
    = menu_link_to(t("nav.edit"), edit_task_path(@task), "edit", class: "info btn-flat")
    = menu_link_to(t("nav.delete"), task_path(@task), "delete", method: :delete, data: { confirm: t(".confirm_destroy") }, class: "danger btn-flat")
    
  %h5= @task.activity_form_name
  .card-content
    %ul.contact-information
      - if @task.activity_form.present?
        %li.left
          %i.material-icons.left
            today
          = @task.deadline
      - if @task.status.present?
        %li.left
        %i.material-icons.left
          = "access_time" if @task.in_progress?
          = "check" if @task.accomplished?
          = "close" if @task.failed?
        = @task.status
  %p
    .container
      .row
        %b.col.s1= t(".description")
        .col.s11= @task.description
    .left-align
      - if @task.in_progress?
        = menu_link_to(t(".pass"), task_path(@task, task: {taskable: @task.taskable, status: "accomplished"}), "check", method: :patch, class: "success btn-flat")
        = menu_link_to(t(".fail"), task_path(@task, task: {taskable: @task.taskable, status: "failed"}), "close", method: :patch, class: "danger btn-flat")