config/routes.rb
Rails.application.routes.draw do
  
  # Ewidencja
  resources :teams do
    resources :schools, only: [:edit, :update, :new, :create, :destroy] do
      resources :officials, only: [:edit, :update, :new, :create, :destroy]
    end
    resources :scouts, only: [:show, :edit, :update, :new, :create, :destroy] do
      resources :parents, only: [:edit, :update, :new, :create, :destroy]
      resources :individual_tasks, only: [:index, :edit, :update, :new, :create, :destroy]
    end
    resources :goals, only: [:index, :edit, :update, :new, :create, :destroy]
  end
  
  # Edukacja
  resources :tasks
  
  # Planowanie
  resources :events do
    resource :sort_activities_order, only: [:edit, :update], controller: 'activities/sort_order'
    resources :activities, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :execution_reports, only: [:index]
  end
  
  # Ocena
  delete "scores/:team_id", to: "scores#clear", as: "clear_scores"
  resources :scores, only: [:index, :show, :new, :create, :destroy]
  
  # Zarządzanie danymi
  
  resources :profiles, only: [:edit, :update]
  
  get "home/download_pdf"
  
  get '/admin', to: 'admin#index'
  namespace :admin do
    resources :abilities
    resources :activity_forms
    resources :character_traits, only: [:index, :edit, :update, :new, :create, :destroy]
  end
  
  root to: 'home#index'

  devise_for :users

end

app/models/score.rb
class Score < ActiveRecord::Base

  # Associations
  belongs_to :scorable, polymorphic: true
  belongs_to :scout
  
  # Validations
  validates :number, presence: true
    
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :load_and_authorize_score,
    only: [:edit, :update, :destroy]
  before_action :set_breadcrumbs

  def index
    authorize Team
    @teams = policy_scope(Team).page(params[:page]).per(1)
    @teams = PaginatingDecorator.decorate(@teams, with: TeamDecorator)
  end

  def show
    @scout = Scout.find(params[:id])
    @scout = ScoutDecorator.decorate(@scout)
    
    @scores = @scout.scores
    add_breadcrumb @scout.full_name
  end

  def new
    @score = params[:score].present? ? Score.new(score_params) : Score.new
    authorize @score
    add_breadcrumb ScoutDecorator.decorate(@score.scout).full_name, score_path(@score.scout)
    add_breadcrumb t(".title")
  end

  def create
    @score = Score.new(score_params)
    authorize @score

    if @score.save
      redirect_to score_path(@score.scout_id), notice: t(".notice")
    else
      render :new
    end
  end

  def destroy
    @score.destroy
    redirect_to score_path(@score.scout_id), notice: t(".notice")
  end
  
  def clear 
    @team = policy_scope(Team).find(params[:team_id])
    @team.scouts.map(&:scores).map(&:delete_all)
    redirect_to scores_path, notice: t(".notice")
  end

  private

  def load_and_authorize_score
    @score = Score.find(params[:id])
    authorize @score
  end

  def score_params
    params.require(:score).permit(*policy(@score || Score).permitted_attributes)
  end
  
  def set_breadcrumbs
    add_breadcrumb t("menu.rating"), scores_path
  end
end

app/views/scores/_activities.html.haml
.right
  = menu_link_to(t(".sort_order"), edit_event_sort_activities_order_path(event), "sort", class: "btn-flat info")
%h5= t(".title")
%table
  %thead
    %tr
      %th= t(".name")
      %th= t(".activity_form")
      %th= t(".description")
      %th= t(".estimated_time_short")
      %th= icon_link_to("#", "edit", class: "inactive")
      %th= icon_link_to("#", "delete", class: "inactive")

  %tbody
    - activities.each do |activity|
      %tr
        %td= activity.name
        %td
          - activity.activity_forms.each do |af|
            .tile.info-inverted= af.name
        %td= activity.description
        %td= activity.estimated_time
        %td= icon_link_to(edit_event_activity_path(event, activity), "edit")
        %td= icon_link_to(event_activity_path(event, activity), "delete", method: :delete, 
          data: { confirm: t(".confirm_destroy") }, class: "danger")

app/views/scores/_form.html.haml
= simple_form_for(@score, html: { class: 'form-horizontal' }) do |f|

  - if @score.errors.any?
    #error_explanation
      %h5= t("activerecord.errors.message", count: @score.errors.count)
      %ul
        - @score.errors.full_messages.each do |msg|
          %li= msg

  = f.association :scout, as: :hidden

  .row
    .input-field.col.s4
      = f.input :number
    .input-field.col.s8
      = f.text_field :reason
      = f.label :reason

  = submit_button_for t("nav.send"), icon="send"

app/views/scores/index.html.haml
- content_for :title do
  = t(".title")
- content_for :notice do
  = notice
- content_for :breadcrumbs do
  = render_breadcrumbs
  
- @teams.each do |team|
  .right
    = button_link_to t(".clear"), clear_scores_path(team), "delete", true, method: :delete, data: { confirm: t(".confirm_destroy") }, class: "danger"
  %h5= team.short_name

  %table
    %thead
      %tr
        %th= t(".scout")
        %th= t(".score_sum")
        %th
        %th
        %th= icon_link_to("#", "add", class: "inactive")

    %tbody
      - team.scouts.sort_by(&:score_sum).reverse.each do |scout|
        %tr
          %td= link_to ScoutDecorator.decorate(scout).full_name, team_scout_path(team, scout)
          %td= scout.score_sum
          %td
          %td= menu_link_to t("nav.show"), score_path(scout.id), "assignment"
          %td= icon_link_to new_score_path(score: {scout_id: scout.id}), "add"
        
= paginate @teams

app/views/scores/new.html.haml
- content_for :title do
  = t(".title")
- content_for :breadcrumbs do
  = render_breadcrumbs

= render 'form'

app/views/scores/show.html.haml
- content_for :notice do
  = notice
- content_for :action_button do
  = icon_link_to new_score_path(score: {scout_id: @scout.id}), "add",
    class: "action-button waves-effect"
- content_for :breadcrumbs do
  = render_breadcrumbs
  
%h5= @scout.full_name

%table
  %thead
    %tr
      %th= t(".reason")
      %th= t(".number")
      %th
      %th= icon_link_to("#", "delete", class: "inactive")

  %tbody
    - @scores.each do |score|
      %tr
        %td= score.reason
        %td= score.number
        %td
        %td= icon_link_to score, "delete", method: :delete, data: { confirm: t(".confirm_destroy") }, class: "danger"    