config/routes.rb
Rails.application.routes.draw do
  
  # Ewidencja
  resources :teams do
    resources :schools, only: [:edit, :update, :new, :create, :destroy] do
      resources :officials, only: [:edit, :update, :new, :create, :destroy]
    end
    resources :scouts, only: [:show, :edit, :update, :new, :create, :destroy] do
      resources :parents, only: [:edit, :update, :new, :create, :destroy]
      resources :individual_tasks, only: [:index, :edit, :update, :new, :create, :destroy]
    end
    resources :goals, only: [:index, :edit, :update, :new, :create, :destroy]
  end
  
  # Edukacja
  resources :tasks
  
  # Planowanie
  resources :events do
    resource :sort_activities_order, only: [:edit, :update], controller: 'activities/sort_order'
    resources :activities, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :execution_reports, only: [:index]
  end
  
  # Ocena
  delete "scores/:team_id", to: "scores#clear", as: "clear_scores"
  resources :scores, only: [:index, :show, :new, :create, :destroy]
  
  # Zarządzanie danymi
  
  resources :profiles, only: [:edit, :update]
  
  get "home/download_pdf"
  
  get '/admin', to: 'admin#index'
  namespace :admin do
    resources :abilities
    resources :activity_forms
    resources :character_traits, only: [:index, :edit, :update, :new, :create, :destroy]
  end
  
  root to: 'home#index'

  devise_for :users

end

app/models/scout.rb
class Scout < ActiveRecord::Base

  pesel_attr :pesel

  # Associations
  belongs_to :team
  belongs_to :school
  has_one :address, as: :addressable, dependent: :destroy
  has_and_belongs_to_many :character_traits
  has_many :parents, as: :relatable, class_name: "RelatedPerson", dependent: :destroy
  has_many :individual_tasks, as: :taskable, class_name: "Task", dependent: :destroy
  has_many :scores, dependent: :destroy
  
  has_attached_file :avatar, :styles => { :medium => "400x500>" }
  
  accepts_nested_attributes_for :address
  
  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, format: { with: /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}/ }, allow_blank: true
  validates :pesel, pesel: true
  validates_attachment_content_type :avatar, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    
  # Enums
  enum rank: %i(no_rank youngster scout pioneer eagle_scout scout_of_the_republic )
  enum position: %i(no_position songster chronicler photographer pennant_bearer
  patrol_leader adjutant)
  
  def born_on
    @born_on ||= pesel_personal_data.date_of_birth rescue nil
  end
  
  def age
    if born_on.present?
      now = Time.now.utc.to_date
      years = now.year - born_on.year
      @age ||= years - (born_on.years_since(years) > now ? 1 : 0)
    end
  end
  
  def score_sum
    scores.pluck(:number).sum
  end
  
end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  before_action :load_and_authorize_team
  before_action :load_and_authorize_scout,
    only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumbs

  def show
    @scout = ScoutDecorator.decorate(@scout)
    @parents = PaginatingDecorator.decorate(@scout.parents, with: RelatedPersonDecorator)
    add_breadcrumb @scout.full_name
  end

  def new
    @scout = @team.scouts.build
    @scout.build_address
    authorize @scout
    add_breadcrumb t(".title")
  end

  def edit
    add_breadcrumb ScoutDecorator.decorate(@scout).full_name, team_scout_path(@team, @scout)
    add_breadcrumb t(".title")
  end

  def create
    @scout = Scout.new(scout_params)
    authorize @scout

    if @scout.save
      redirect_to team_scout_path(@team, @scout), notice: t(".notice")
    else
      render :new
    end
  end

  def update
    if @scout.update(scout_params)
      redirect_to team_scout_path(@team, @scout), notice: t(".notice")
    else
      render :edit
    end
  end

  def destroy
    @scout.destroy
    redirect_to team_url(@team), notice: t(".notice")
  end

  private

  def load_and_authorize_scout
    @scout = Scout.find(params[:id])
    authorize @scout
  end
  
  def load_and_authorize_team
    @team = Team.find(params[:team_id])
    @team = TeamDecorator.decorate(@team)
    authorize @team
  end

  def scout_params
    params.require(:scout).permit(*policy(@scout || Scout).permitted_attributes)
  end
  
  def set_breadcrumbs
    add_breadcrumb t("menu.registry"), teams_path
    add_breadcrumb @team.short_name, team_path(@team)
  end
end

app/helpers/scouts_helper.rb
module ScoutsHelper

  def rank_options_for_select
    Scout.ranks.keys.map do |key|
      [I18n.t("enumerations.scout.rank.#{key}"), key]
    end
  end
  
  def position_options_for_select
    Scout.positions.keys.map do |key|
      [I18n.t("enumerations.scout.position.#{key}"), key]
    end
  end
  
  def scout_school_collection(scout)
    PaginatingDecorator.decorate(scout.team.schools, with: SchoolDecorator)
  end
  
end

app/views/scouts/_form.html.haml
= simple_form_for(@scout, url: url, html: { class: 'form-horizontal' }) do |f|
  - if @scout.errors.any?
    #error_explanation
      %h5= t("activerecord.errors.message", count: @scout.errors.count)
      %ul
        - @scout.errors.full_messages.each do |msg|
          %li= msg
          
  .row  
    .input-field.col.s5
      = f.text_field :first_name
      = f.label :first_name
    .input-field.col.s5
      = f.text_field :last_name
      = f.label :last_name
    .input-field.col.s2
      = f.text_field :pesel
      = f.label :pesel
  .row
    .input-field.col.s6
      = f.text_field :birthplace
      = f.label :birthplace
    .input-field.col.s6
      = f.input :avatar, input_html: { class: "image-input-button" }, label: false
      = f.label :avatar, active: true
  .row
    .input-field.col.s4
      = f.association :team, :collection => policy_scope(Team.all), :value_method => :id, include_blank: false
      = f.label :team
    .input-field.col.s4
      = f.text_field :patrol
      = f.label :patrol
    .input-field.col.s4
      = f.select :position, position_options_for_select, include_blank: false
      = f.label :position, active: false
  .row
    .input-field.col.s4
      = f.select :rank, rank_options_for_select, include_blank: false
      = f.label :rank, active: false
    .input-field.col.s4
      = f.text_field :promise_made_on, as: :date, class: 'datepicker'
      = f.label :promise_made_on
      - if action_name == 'edit'
        = f.hint "Wybierz datę ponownie"
      
  %h5 Informacje kontaktowe
  .row
    .input-field.col.s6
      %i.material-icons.prefix
        phone
      = f.text_field :phone_number
      = f.label :phone_number
    .input-field.col.s6
      %i.material-icons.prefix
        email
      = f.text_field :email
      = f.label :email
  .row
    = f.simple_fields_for :address do |fa|
      .input-field.col.s6
        %i.material-icons.prefix
          home
        = fa.text_field :street_and_number
        = label_for_nested(:street_and_number, :address, @scout)
      .input-field.col.s2
        = fa.text_field :postal_code
        = label_for_nested(:postal_code, :address, @scout)
      .input-field.col.s4
        = fa.text_field :city
        = label_for_nested(:city, :address, @scout)
        
  %h5 Informacje o szkole
  .row
    .input-field.col.s8
      = f.association :school, :collection => scout_school_collection(@scout), 
      :value_method => :id, label_method: :full_name, label: false
      = f.label :school, active: true
    .input-field.col.s4
      = f.text_field :grade
      = f.label :grade 
      
  %h5 Charakterystyka
  .row
    .input-field.col.s6
      .success= t(".strengths")
      .collection-check-boxes
        = collection_check_boxes :scout, :character_trait_ids, 
        CharacterTrait.strength.order(:name), :id, :name
        
    .input-field.col.s6
      .danger= t(".weaknesses")
      .collection-check-boxes
        = collection_check_boxes :scout, :character_trait_ids, 
        CharacterTrait.weakness.order(:name), :id, :name
  
  %h5 Informacje zdrowotne
  .row
    .input-field.col.s4
      = f.text_area :allergies, class: "materialize-textarea"
      = f.label :allergies
    .input-field.col.s4
      = f.text_area :past_diseases, class: "materialize-textarea"
      = f.label :past_diseases
    .input-field.col.s4
      = f.text_area :vaccinations, class: "materialize-textarea"
      = f.label :vaccinations

  = submit_button_for t("nav.send"), icon="send"
  

app/views/scouts/_parents.html.haml
%b= t(".title")
%ul.contact-information
  - parents.each do |parent|
    %li
      = parent.full_name_with_role
      .right
        = icon_link_to(edit_team_scout_parent_path(team, scout, parent), "edit", class: "blend-in")
        = icon_link_to(team_scout_parent_path(team, scout, parent), "delete", method: :delete,
          data: { confirm: t(".confirm_destroy") }, class: "blend-in")
      %ul.contact-information
        - if parent.phone_number.present?
          %li
            %i.material-icons.left
              phone
            = parent.phone_number
        - if parent.email.present?
          %li
            %i.material-icons.left
              email
            = parent.email
.right-align
  = menu_link_to t(".add"), new_team_scout_parent_path(@team, @scout), "add", class: "blend-in btn-flat"

app/views/scouts/edit.html.haml
- content_for :title do
  = t(".title")
- content_for :breadcrumbs do
  = render_breadcrumbs

= render 'form', url: team_scout_path(@team, @scout)

app/views/scouts/new.html.haml
- content_for :title do
  = t(".title")
- content_for :breadcrumbs do
  = render_breadcrumbs

= render 'form', url: team_scouts_path(@team)

app/views/scouts/show.html.haml
- content_for :notice do
  = notice
- content_for :action_button do
  = icon_link_to team_scout_individual_tasks_path(@team, @scout), "school", 
    class: "action-button waves-effect"
- content_for :breadcrumbs do
  = render_breadcrumbs
  
.row
  .col.s7
    .card-panel
      %table
        %thead
          %tr
            %td{colspan: "2"}
              = t(".scouting_information")
        %tbody
          %tr
            %td.prompt= t(".patrol")
            %td= @scout.patrol
          %tr
            %td.prompt= t(".position")
            %td= @scout.position
          %tr
            %td.prompt= t(".rank")
            %td= @scout.rank
          %tr
            %td.prompt= t(".promise_made_on")
            %td= @scout.promise_made_on
    .card-panel
      %table
        %thead
          %tr
            %td{colspan: "2"}
              = t(".school_information")
        %tbody
          %tr
            %td.prompt= t(".school_name")
            %td= @scout.school.full_name if @scout.school.present?
          %tr
            %td.prompt= t(".school_address")
            %td= @scout.school.address if @scout.school.present?
          %tr
            %td.prompt= t(".school_class")
            %td= @scout.grade

    .card-panel
      %table
        %thead
          %tr
            %td{colspan: "2"}
              = t(".characteristic")
        %tbody
          %tr
            %td.prompt= t(".strengths")
            %td
              - @scout.character_traits.strength.each do |s|
                .tile.success-inverted= s.name
          %tr
            %td.prompt= t(".weaknesses")
            %td
              - @scout.character_traits.weakness.each do |w|
                .tile.danger-inverted= w.name

    .card-panel
      %table
        %thead
          %tr
            %td{colspan: "2"}
              = t(".health_information")
        %tbody
          %tr
            %td.prompt= t(".allergies")
            %td= @scout.allergies
          %tr
            %td.prompt= t(".past_diseases")
            %td= @scout.past_diseases
          %tr
            %td.prompt= t(".vaccinations")
            %td= @scout.vaccinations

  .col.s5
    .card
      .card-image
        - if @scout.avatar.present?
          = image_tag @scout.avatar.url(:medium)
        - else
          .default-avatar
            %i.material-icons.enormous
              person
        %span.image-card-title
          .image-title
            = @scout.full_name
          .image-subtitle
            = @scout.age_with_unit
          .image-description
            %b= t(".pesel")
            = @scout.pesel
          .image-description
            %b= t(".birthplace")
            = @scout.birthplace
      .card-content
        %ul.contact-information
          - if @scout.phone_number.present?
            %li
              %i.material-icons.left
                phone
              = @scout.phone_number
          - if @scout.email.present?
            %li
              %i.material-icons.left
                email
              = @scout.email
          - if @scout.street_and_number.present? || @scout.city_with_postal_code.present?
            %li
              %i.material-icons.left
                home
              = @scout.street_and_number
              %br
              = @scout.city_with_postal_code
      .alt-card-content
        = render "parents", team: @team, scout: @scout, parents: @parents
      .card-content.center-align
        %ul.actions
          %li= menu_link_to(t("nav.edit"), edit_team_scout_path(@team, @scout), "edit", class: "info btn-flat")
          %li= menu_link_to(t("nav.delete"), team_scout_path(@team, @scout), "delete", method: :delete, 
            data: { confirm: t(".confirm_destroy") }, class: "danger btn-flat")