config/routes.rb
Rails.application.routes.draw do
  
  # Ewidencja
  resources :teams do
    resources :schools, only: [:edit, :update, :new, :create, :destroy] do
      resources :officials, only: [:edit, :update, :new, :create, :destroy]
    end
    resources :scouts, only: [:show, :edit, :update, :new, :create, :destroy] do
      resources :parents, only: [:edit, :update, :new, :create, :destroy]
      resources :individual_tasks, only: [:index, :edit, :update, :new, :create, :destroy]
    end
    resources :goals, only: [:index, :edit, :update, :new, :create, :destroy]
  end
  
  # Edukacja
  resources :tasks
  
  # Planowanie
  resources :events do
    resource :sort_activities_order, only: [:edit, :update], controller: 'activities/sort_order'
    resources :activities, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :execution_reports, only: [:index]
  end
  
  # Ocena
  delete "scores/:team_id", to: "scores#clear", as: "clear_scores"
  resources :scores, only: [:index, :show, :new, :create, :destroy]
  
  # Zarządzanie danymi
  
  resources :profiles, only: [:edit, :update]
  
  get "home/download_pdf"
  
  get '/admin', to: 'admin#index'
  namespace :admin do
    resources :abilities
    resources :activity_forms
    resources :character_traits, only: [:index, :edit, :update, :new, :create, :destroy]
  end
  
  root to: 'home#index'

  devise_for :users

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  after_initialize :set_execution_report

  # Associations
  belongs_to :event
  has_and_belongs_to_many :activity_forms, join_table: "activity_forms_activities"
  has_one :execution_report, dependent: :destroy
  
  accepts_nested_attributes_for :execution_report
  
  # Validations
  validates :name, presence: true
  validates :estimated_time, presence: true
  
  # Scopes
  scope :ordered, -> { order("position") }
  
  private
  
  def set_execution_report
    build_execution_report if execution_report.nil?
  end
  
end

app/models/activity_form.rb
class ActivityForm < ActiveRecord::Base

  # Associations
  belongs_to :educational_method
  has_and_belongs_to_many :activities, join_table: "activity_forms_activities"
  has_and_belongs_to_many :character_traits, join_table: "activity_forms_traits"
  has_many :tasks, dependent: :destroy
  
  # Validations
   validates :name, presence: true
   validates :name, uniqueness: true
  
end

app/controllers/activities/sort_order_controller.rb
class Activities::SortOrderController < ApplicationController
  before_action :load_and_authorize_event
  before_filter :set_breadcrumbs

  def edit
    @activities = @event.activities.ordered
    authorize Activity, :sort_order?
    add_breadcrumb t(".title")
  end

  def update
    authorize Activity, :sort_order?
    
    params[:activities].each_with_index do |id, index|
      Activity.where(id: id).update_all(position: index)
    end
    
    redirect_to event_url(@event), notice: t(".notice")
  end

  private
  
  def load_and_authorize_event
    @event = Event.find(params[:event_id])
    @event = EventDecorator.decorate(@event)
    authorize @event
  end

  def set_breadcrumbs
    add_breadcrumb t("menu.planning"), events_path
    add_breadcrumb @event.starts_on, event_path(@event)
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :load_and_authorize_event
  before_action :load_and_authorize_activity,
    only: [:edit, :update, :destroy]
  before_action :set_breadcrumbs
  
  def index
    authorize Activity
    @activities = @event.activities.ordered.page(params[:page]).per(20)
    @activities = PaginatingDecorator.decorate(@activities, with: ActivityDecorator)
    add_breadcrumb t(".title")
  end
  
  def new
    @activity = if params[:activity].present?
      @event.activities.build(activity_params)
    else
      @event.activities.build
    end

    authorize @activity
    add_breadcrumb t(".title")
  end

  def edit
    add_breadcrumb @activity.name
    add_breadcrumb t(".title")
  end

  def create
    @activity = Activity.new(activity_params)
    set_position
    authorize @activity
    
    if @activity.save
      redirect_to event_path(@event), notice: t(".notice")
    else
      render :new
    end
  end

  def update
    if @activity.update(activity_params)
      redirect_to event_path(@event), notice: t(".notice")
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to event_path(@event), notice: t(".notice")
  end

  private
  
  def set_position
    last_position = @event.activities.pluck(:position).sort.last || 0
    @activity.position = last_position + 1
  end
  
  def load_and_authorize_activity
    @activity = Activity.find(params[:id])
    authorize @activity
  end
  
  def load_and_authorize_event
    @event = Event.find(params[:event_id])
    @event = EventDecorator.decorate(@event)
    authorize @event
  end
  
  def activity_params
    params.require(:activity).permit(*policy(@activity || Activity).permitted_attributes)
  end
  
  def set_breadcrumbs
    add_breadcrumb t("menu.planning"), events_path
    add_breadcrumb @event.starts_on, event_path(@event)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def activity_form_options_for_select
    ActivityForm.all.map do |af|
      [af.name, af.id]
    end
  end
  
  def activity_event_collection
    PaginatingDecorator.decorate(policy_scope(Event.all), with: EventDecorator)
  end
  
end

app/views/activities/_form.html.haml
= simple_form_for(@activity, url: url, html: { class: 'form-horizontal' }) do |f|

  - if @activity.errors.any?
    #error_explanation
      %h5= t("activerecord.errors.message", count: @activity.errors.count)
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg
  
  .row
    .input-field.col.s4
      = f.association :event, :collection => activity_event_collection, :value_method => :id, label_method: :starts_on, label: false, include_blank: false
      = f.label :event
    .input-field.col.s4
      = f.text_field :name
      = f.label :name
    .input-field.col.s4
      = f.text_field :estimated_time
      = f.label :estimated_time
      = f.hint "w minutach"
      
  %h5 Formy pracy
  .row
    .input-field.col.s12
      .collection-check-boxes
        = collection_check_boxes :activity, :activity_form_ids, 
        ActivityForm.order(:name), :id, :name
        
  .row
    .input-field.col.s12
      = f.text_area :description, class: "materialize-textarea"
      = f.label :description
      
  %h5 Raport
  .row
    = f.simple_fields_for :execution_report do |fa|
      .input-field.col.s12
        %i.material-icons.prefix
          report
        = fa.text_area :content, class: "materialize-textarea"
        = label_for_nested(:content, :execution_report, @activity)

  = submit_button_for t("nav.send"), icon="send"

app/views/activities/edit.html.haml
- content_for :title do
  = t(".title")
- content_for :breadcrumbs do
  = render_breadcrumbs

= render 'form', url: event_activity_path(@event, @activity)

app/views/activities/index.html.haml
- content_for :title do
  = t(".title")
- content_for :notice do
  = notice
- content_for :action_button do
  %a.action-button.waves-effect{:href => event_execution_reports_path(@event, format: :pdf)}
    %i.material-icons 
      file_download
- content_for :breadcrumbs do
  = render_breadcrumbs
  
%h5= @event.duration_time
.card-content
  %ul.contact-information
    - if @event.place.present?
      %li.left
        %i.material-icons.left
          place
        = @event.place
    - if @event.team.present?
      %li.left
      %i.material-icons.left
        flag
      = @event.team.short_name
%table
  %thead
    %tr
      %th= t(".plan_description")
      %th= t(".execution_report")

  %tbody
    - @activities.each do |activity|
      %tr
        %td
          %b= activity.name
          %br
          = activity.description
        %td= activity.execution_report_content

app/views/activities/new.html.haml
- content_for :title do
  = t(".title")
- content_for :breadcrumbs do
  = render_breadcrumbs

= render 'form', url: event_activities_path(@event)

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Event:
  = @activity.event
%p
  %b Activity form:
  = @activity.activity_form
%p
  %b Description:
  = @activity.description

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path